spring.application.name=worksync

spring.datasource.url=jdbc:postgresql://localhost:5432/worksync
spring.datasource.username=postgres
spring.datasource.password=Pollux2020

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
#spring.sql.init.mode=always

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.defer-datasource-initialization=true
